/**
 * UserData represents the User Data Parameters(user_data) of a Conversions API Event Request.
 * 'user_data' is a set of identifiers Facebook can use for targeted attribution. See Custom Audiences from CRM Data for details on how to normalize and hash the data you send.
 * @see {@link https://developers.facebook.com/docs/marketing-api/conversions-api/parameters/customer-information-parameters}
 *
 * @param {String} email An email address, in lowercase.
 * @param {String} phone A phone number. Include only digits with country code, area code, and number.
 * @param {String} gender Gender, in lowercase. Either f or m.
 * @param {String} first_name A first name in lowercase.
 * @param {String} last_name A last name in lowercase.
 * @param {String} date_of_birth A date of birth given as year, month, and day in YYYYMMDD format.
 * @param {String} city A city in lower-case without spaces or punctuation.
 * @param {String} state A two-letter state code in lowercase.
 * @param {String} zip Postal code of the city in your country standard
 * @param {String} country A two-letter country code in lowercase.
 * @param {String} external_id Any unique ID from the advertiser,
 * @param {String} client_ip_address The IP address of the browser corresponding to the event.
 * @param {String} client_user_agent The user agent for the browser corresponding to the event.
 * @param {String} fbp The Facebook click ID value stored in the _fbc browser cookie under your domain.
 * @param {String} fbc The Facebook browser ID value stored in the _fbp browser cookie under your domain.
 * @param {String} subscription_id The subscription ID for the user in this transaction.
 * @param {String} fb_login_id The FB login ID for the user.
 * @param {String} lead_id The Id associated with a lead generated by Facebook's Lead Ads.
 * @param {String} dobd The date of birth day in DD format.
 * @param {String} dobm The date of birth month in MM format.
 * @param {String} doby The date of birth year in YYYY format.
 * @param {String} madid
 * @param {String} anon_id
 * @param {String} app_user_id
 */

export interface UserData {
  _emails: string[];
  _phones: string[];
  _genders: string[];
  _first_names: string[];
  _last_names: string[];
  _dates_of_birth: string[];
  _cities: string[];
  _states: string[];
  _zips: string[];
  _countries: string[];
  _external_ids: string[];
  _client_ip_address: string;
  _client_user_agent: string;
  _fbc: string;
  _fbp: string;
  _subscription_id: string;
  _fb_login_id: string;
  _lead_id: string;
  _f5first: string;
  _f5last: string;
  _fi: string;
  _dobd: string;
  _dobm: string;
  _doby: string;
  _madid: string;
  _anon_id: string;
  _app_user_id: string;
}
